/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with Apple; creates the account on first sign-in
         * @description The identity token is checked against Apple's public keys (signature, issuer, audience, expiry) and the nonce
         *     the phone sent to Apple. Answers a session; `newAccount` tells the app to start onboarding.
         */
        post: operations["signInWithApple"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trade a refresh token for a new session */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session and revoke its refresh token */
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete the account and every record of it, in every module */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/account/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything held about the user, as JSON */
        get: operations["exportAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        /** Set the whole profile (onboarding and settings) */
        put: operations["putProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current state of each of the three consents */
        get: operations["listConsents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/consents/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["ConsentKind"];
            };
            cookie?: never;
        };
        get?: never;
        /** Grant a consent to the version of its text the user saw */
        put: operations["grantConsent"];
        post?: never;
        /** Withdraw a consent; the features it covers stop at once */
        delete: operations["withdrawConsent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/weigh-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWeighIns"];
        put?: never;
        post: operations["recordWeighIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/weigh-ins/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteWeighIn"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/weight-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The trend weight per day (7-day average, the engine's WeightTrend)
         * @description One point per day, up to today in the user's time zone, whose 7 days hold at least one weigh-in (the day's first
         *     counts). Needs the profile (NOT_FOUND without one). At most 400 days per request.
         */
        get: operations["getWeightTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/waist-measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWaistMeasurements"];
        put?: never;
        post: operations["recordWaistMeasurement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/photo-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** What the phone concluded from a progress photo; the photo itself never leaves the phone (V1) */
        post: operations["recordPhotoCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/body-looks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The reference look closest to the user's own, as a level (K-224); never a percent in or out (U4)
         * @description The app shows reference looks (the belly test, Ö-4) and sends the level picked, 1 to look_levels (7). The engine
         *     reads it, with the waist, as its internal estimate; no response anywhere carries a percent. Health data:
         *     CONSENT_REQUIRED without the HEALTH_DATA consent.
         */
        post: operations["recordBodyLook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/activity-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** A day's steps, sleep and active energy from Apple Health (replaces that day's values) */
        put: operations["putActivityDay"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/foods/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search the food database by name
         * @description A POST so the search words stay out of URLs and access logs (V3).
         */
        post: operations["searchFoods"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/foods/barcode-lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The product with this barcode (USDA FDC Branded Foods, ADR-008)
         * @description A POST so the barcode stays out of URLs and access logs (V3). NOT_FOUND when FDC has no such product.
         */
        post: operations["lookUpBarcode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/food-estimates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match food and amounts to the database and answer ranges (U1, U5); nothing is stored
         * @description The estimate comes from the database, never from a language model's numbers. When one item dominates the
         *     range, `question` asks the one thing that would narrow it (at most one question).
         */
        post: operations["estimateFood"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMeals"];
        put?: never;
        /**
         * Log a meal from items, or repeat an earlier meal ("same as yesterday")
         * @description Stored with the ranges as estimated now, on the user's local day at eatenAt (the profile's time zone). repeatOf
         *     is one of the user's own meals (else NOT_FOUND); its items are logged again as they were.
         */
        post: operations["logMeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/meals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteMeal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/days/{day}/budget": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        /**
         * What is left of the day's target, as a range (target minus the logged range)
         * @description NOT_FOUND until the user has a target (set by calls, K-216). Health data: CONSENT_REQUIRED without the
         *     HEALTH_DATA consent, as for every /v1/meals route.
         */
        get: operations["getDayBudget"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The exercise catalog */
        get: operations["listExercises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/program": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current program with this week's targets */
        get: operations["getProgram"];
        /** Bring your own program; the engine coaches on top of it. Replaces the current one */
        put: operations["putOwnProgram"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/program/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build a program for the days the user has (4-day upper/lower by default); replaces the current one */
        post: operations["generateProgram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkouts"];
        put?: never;
        post: operations["startWorkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getWorkout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workouts/{id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finishWorkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workouts/{id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description A clientId already used for a set of another workout is 409 CONFLICT, not a replay. */
        post: operations["logSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workouts/{id}/sets/{setId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                setId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/check-ins/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This week's check-in and the few questions it needs (question budget, U9)
         * @description Only what the data does not already say is asked: weight, steps, sleep hours and training arrive on their own;
         *     how it looks comes from the week's photo check (from seven days before the check-in day) and the waist from its
         *     measurements. A question is asked only when
         *     the engine would wait for its answer this week (found by running it on the data and on each possible answer), at
         *     most question_budget_per_week (question_budget_per_week_anomaly when the photo or waist disagrees with the phase).
         *     No questions, and `answered`, once the week has its call — or once the last call's week overlaps it (the check-in
         *     day moved). Choice texts: checkIn.choice.<kind>.<choice lowercased>.
         */
        get: operations["getCurrentCheckIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/check-ins/current/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer the check-in; the engine makes this week's call
         * @description The answers name their week (`weekOf`). Sent again with the same clientId, the stored call comes back (200) and
         *     the engine does not run twice; answers for a week that is not the current one, a second call this week, a user
         *     without a profile yet, or a goal of DECIDE_FOR_ME (its direction needs the phase gate) are 409 CONFLICT. Health
         *     data: CONSENT_REQUIRED without the HEALTH_DATA consent, as for every /v1/decisions route. Taken: TRAINING and
         *     RECOVERY, the questions the engine can wait for — also when the data has changed since they were asked, so a
         *     question shown is never refused. Any other kind is VALIDATION_FAILED (400): how it looks and the waist come from
         *     the data, the rest are read with their own questions later (CYCLE_STOPPED waits for the energy band, K-212).
         */
        post: operations["answerCheckIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every call so far, newest first (the call ledger) */
        get: operations["listDecisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decisions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The call in force and the targets it set
         * @description NOT_FOUND before the first check-in has produced a call.
         */
        get: operations["getCurrentDecision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decisions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get: operations["getDecision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decisions/{id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply the call; only the one thing it changes moves, everything else stays (U3)
         * @description Only the latest call, only while PENDING, and only on the plan target it judged (else 409: another call moved the
         *     plan while this one was being made). Applied twice (or by two requests at once), the targets move once. A
         *     calorie call moves the calorie target (and restarts its wait); more movement raises the step target. CONFLICT (409):
         *     an older call, one that changes nothing (NOT_NEEDED), one undone, a training call without a program to change,
         *     and a call whose kind is not applied yet — a phase change, a mini cut and the hard stop need what the engine
         *     cannot read yet. The deload ladder's calls change the program (K-217): hold the load from today; a lighter week or
         *     a week off from today to the day before the call's nextReview. NOT_FOUND for an unknown id. Health data:
         *     CONSENT_REQUIRED without the HEALTH_DATA consent.
         */
        post: operations["applyDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decisions/{id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Put the targets back as they were before the call was applied (kept in the audit trail)
         * @description Only the latest call, and only once APPLIED; undone twice, nothing more changes. An undone call is not applied
         *     again (CONFLICT). The call keeps appliedAt and undoneAt.
         */
        post: operations["undoDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The targets the user follows today
         * @description NOT_FOUND before the first estimate (no plan, or no weigh-in when it began). The macros split the calorie target
         *     at today's trend weight, or the last weight known however old. The food budget (/v1/days/{day}/budget) reads the
         *     same targets.
         */
        get: operations["getTargets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/coach/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask about a call or the plan; the coach explains, it does not decide (U1)
         * @description The question goes to a third-party language model, so it needs the THIRD_PARTY_AI consent (V2); without it the
         *     answer is 403 CONSENT_REQUIRED. Quota: coach_messages_per_day (429 RATE_LIMITED).
         */
        post: operations["askCoach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "UP";
        };
        /** @description Shared error body. Messages never contain health data (anayasa V3). */
        Error: {
            /** @description Stable machine-readable code, e.g. VALIDATION_FAILED, NOT_FOUND, CONSENT_REQUIRED. */
            code: string;
            /** @description English, safe to show to the user. */
            message: string;
        };
        /** @description An energy estimate, kcal a day or a meal, as a range (U5). low ≤ high. */
        KcalRange: {
            low: number;
            high: number;
        };
        /** @description A macro estimate in grams, as a range (U5). low ≤ high. */
        GramRange: {
            low: number;
            high: number;
        };
        /** @description What is left of a target, as a range; negative when the day went past it. low ≤ high. */
        KcalBalance: {
            low: number;
            high: number;
        };
        /** @description Grams left of a target, as a range; negative past it. low ≤ high. */
        GramBalance: {
            low: number;
            high: number;
        };
        Left: {
            kcal: components["schemas"]["KcalBalance"];
            proteinG: components["schemas"]["GramBalance"];
        };
        /**
         * Format: uuid
         * @description Made by the phone when the record is created; the same record sent again is stored once.
         */
        ClientId: string;
        AppleSignIn: {
            /** @description The JWT Apple gave the phone. */
            identityToken: string;
            /** @description The raw nonce the phone hashed into its Apple request. */
            nonce: string;
            /**
             * @description Apple's one-time code, exchanged on the server for the refresh token that account deletion must revoke
             *     (K-214; Apple's rule on deleting accounts that use Sign in with Apple — verified in K-203).
             */
            authorizationCode?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        Session: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            refreshToken: string;
            /** @description True on the first sign-in; the app starts onboarding. */
            newAccount: boolean;
        };
        /** @description Everything held about the user, one section per module; the shape of each section is that module's. */
        AccountExport: {
            /** Format: date-time */
            exportedAt: string;
            sections: {
                [key: string]: unknown;
            };
        };
        Profile: {
            /**
             * @description What the user wants; the phase itself is the engine's call (K-105).
             * @enum {string}
             */
            goal: "LOSE_FAT" | "BUILD_MUSCLE" | "DECIDE_FOR_ME";
            sex: components["schemas"]["Sex"];
            heightCm: number;
            /**
             * @description Adults only (K-225): only the year is kept, so this year minus birthYear must be at least 19 on the user's
             *     calendar — certainly 18 on every day of the year. Younger is VALIDATION_FAILED.
             */
            birthYear: number;
            activityLevel?: components["schemas"]["ActivityLevel"];
            /** @enum {string} */
            programChoice: "BUILD_ONE_FOR_ME" | "BRING_MY_OWN";
            schedule: components["schemas"]["Schedule"];
            food?: components["schemas"]["FoodPreferences"];
            /** @enum {string} */
            units: "METRIC" | "IMPERIAL";
        };
        /** @enum {string} */
        Sex: "MALE" | "FEMALE";
        /**
         * @description The whole day's activity, training included (K-114). Absent until asked.
         * @enum {string}
         */
        ActivityLevel: "INACTIVE" | "LOW_ACTIVE" | "ACTIVE" | "VERY_ACTIVE";
        /** @enum {string} */
        Weekday: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
        Schedule: {
            trainingDays: components["schemas"]["Weekday"][];
            /** @description Local time, HH:mm; reminders follow it. */
            usualTrainingTime?: string;
            /** @enum {string} */
            sessionsLastMonth?: "NONE_OR_ONE" | "TWO_TO_THREE" | "FOUR" | "FIVE_OR_MORE";
            checkInDay: components["schemas"]["Weekday"];
            /** @description IANA zone, e.g. Europe/Istanbul; the check-in day is the user's local day. */
            timeZone: string;
        };
        FoodPreferences: {
            /**
             * @description Foods the user does not eat or cannot eat, in their own words. May be health data (an allergy, coeliac
             *     disease; GDPR Art. 9): kept only with the HEALTH_DATA consent (CONSENT_REQUIRED without it), and absent from
             *     responses while the consent is not given (K-225).
             */
            avoid?: string[];
            budgetNote?: string;
        };
        /** @enum {string} */
        ConsentKind: "HEALTH_DATA" | "APPLE_HEALTH" | "THIRD_PARTY_AI";
        ConsentGrant: {
            /** @description The version of the consent text the user saw. */
            textVersion: string;
            /** @description THIRD_PARTY_AI only — the company the data goes to, as named on the screen (Apple 5.1.2(i)). */
            provider?: string;
            /** @description THIRD_PARTY_AI only — what is sent, as named on the screen. */
            dataTypes?: string[];
        };
        Consent: {
            kind: components["schemas"]["ConsentKind"];
            /** @enum {string} */
            status: "GRANTED" | "WITHDRAWN" | "NEVER_ASKED";
            textVersion?: string;
            provider?: string;
            dataTypes?: string[];
            /** Format: date-time */
            grantedAt?: string;
            /** Format: date-time */
            withdrawnAt?: string;
        };
        /** @enum {string} */
        MeasurementSource: "MANUAL" | "APPLE_HEALTH" | "IMPORT";
        NewWeighIn: {
            clientId: components["schemas"]["ClientId"];
            /** Format: date-time */
            measuredAt: string;
            /** @description At most 2 decimals (the store keeps 2; a finer value is a validation error, not a silent rounding). */
            kg: number;
            source: components["schemas"]["MeasurementSource"];
        };
        WeighIn: components["schemas"]["NewWeighIn"] & {
            /** Format: uuid */
            id: string;
        };
        TrendPoint: {
            /** Format: date */
            day: string;
            kg: number;
        };
        NewWaistMeasurement: {
            clientId: components["schemas"]["ClientId"];
            /** Format: date */
            measuredOn: string;
            /** @description At most 1 decimal. */
            cm: number;
        };
        WaistMeasurement: components["schemas"]["NewWaistMeasurement"] & {
            /** Format: uuid */
            id: string;
        };
        /**
         * @description The photo compared with the last one, judged on the phone.
         * @enum {string}
         */
        Look: "BETTER" | "SAME" | "WORSE";
        NewBodyLook: {
            clientId: components["schemas"]["ClientId"];
            /** Format: date */
            takenOn: string;
            /** @description The reference look picked, leanest first; what it means is the engine's (U4). */
            level: number;
        };
        BodyLook: components["schemas"]["NewBodyLook"] & {
            /** Format: uuid */
            id: string;
        };
        /** @description Derived on the phone; no image, no measurement of the body leaves it (V1). */
        NewPhotoCheck: {
            clientId: components["schemas"]["ClientId"];
            /** Format: date */
            takenOn: string;
            look: components["schemas"]["Look"];
        };
        PhotoCheck: components["schemas"]["NewPhotoCheck"] & {
            /** Format: uuid */
            id: string;
        };
        ActivityDay: {
            /** Format: date */
            day: string;
            steps?: number;
            sleepMinutes?: number;
            /** @description Apple Health's own figure, passed through as given; any range around it is made on the server. */
            activeEnergyKcal?: number;
        };
        Food: {
            /** @description The database's identifier (USDA FoodData Central, ADR-008). */
            id: string;
            name: string;
            brand?: string;
            per100g: components["schemas"]["Nutrients"];
            servings?: components["schemas"]["Serving"][];
        };
        Nutrients: {
            kcal: components["schemas"]["KcalRange"];
            proteinG: components["schemas"]["GramRange"];
            carbsG: components["schemas"]["GramRange"];
            fatG: components["schemas"]["GramRange"];
        };
        Serving: {
            /** @description e.g. "1 cup", "1 large". */
            name: string;
            grams: number;
        };
        Amount: {
            /** @description At most 2 decimals; the amount it makes is at most 5000 g. */
            quantity: number;
            /**
             * @description grams (g), millilitres (ml: only for a food with a known density) or the name of one of the food's servings
             *     (a serving is a measure: its own range, whatever certainty says).
             */
            unit: string;
            /**
             * @description A weighed amount narrows the range; an estimated one (the default) widens it.
             * @enum {string}
             */
            certainty?: "WEIGHED" | "ESTIMATED";
        };
        FoodSearch: {
            q: string;
            /** @default 20 */
            limit: number;
        };
        BarcodeLookup: {
            /** @description As scanned — EAN-8, UPC-E (expanded by the server), UPC-A, EAN-13 or GTIN-14. A wrong check digit is 400. */
            gtin: string;
        };
        /**
         * @description Structured items only. Free text and meal photos need a language model, which only comes with the third-party
         *     AI consent (M5, V2) — added then, in a later contract version.
         */
        FoodEstimateRequest: {
            items: components["schemas"]["ItemRequest"][];
        };
        ItemRequest: {
            foodId: string;
            amount: components["schemas"]["Amount"];
        };
        EstimatedItem: {
            foodId: string;
            name: string;
            amount: components["schemas"]["Amount"];
            kcal: components["schemas"]["KcalRange"];
            proteinG: components["schemas"]["GramRange"];
            carbsG?: components["schemas"]["GramRange"];
            fatG?: components["schemas"]["GramRange"];
        };
        FoodEstimate: {
            items: components["schemas"]["EstimatedItem"][];
            kcal: components["schemas"]["KcalRange"];
            proteinG: components["schemas"]["GramRange"];
            question?: components["schemas"]["AmountQuestion"];
        };
        /** @description The one question that would narrow the range most, about the item that dominates it. */
        AmountQuestion: {
            foodId: string;
            copyKey: string;
        };
        /** @enum {string} */
        MealSlot: "BREAKFAST" | "LUNCH" | "DINNER" | "SNACK";
        /** @description Either items, or repeatOf (an earlier meal logged again) — exactly one. */
        NewMeal: {
            clientId: components["schemas"]["ClientId"];
            /** Format: date-time */
            eatenAt: string;
            slot: components["schemas"]["MealSlot"];
            items?: components["schemas"]["ItemRequest"][];
            /** Format: uuid */
            repeatOf?: string;
        } & (unknown | unknown);
        Meal: {
            /** Format: uuid */
            id: string;
            clientId: components["schemas"]["ClientId"];
            /** Format: date-time */
            eatenAt: string;
            slot: components["schemas"]["MealSlot"];
            items: components["schemas"]["EstimatedItem"][];
            kcal: components["schemas"]["KcalRange"];
            proteinG: components["schemas"]["GramRange"];
        };
        DayBudget: {
            /** Format: date */
            day: string;
            /** @description The day's target (a plan number, one figure). */
            targetKcal: number;
            eaten: components["schemas"]["Nutrients"];
            left: components["schemas"]["Left"];
        };
        Exercise: {
            id: string;
            /**
             * @description Copy key of the name (en.json, exercises.<id>.name). The search aliases are the app's text too:
             *     exercises.<id>.aliases, comma-separated.
             */
            nameKey: string;
            /** @enum {string} */
            kind: "COMPOUND" | "ISOLATION";
            muscles: string[];
            /** @description Exercise ids that can take its place. */
            alternatives: string[];
            /** @enum {string} */
            load: "EXTERNAL" | "BODYWEIGHT" | "BODYWEIGHT_PLUS_EXTERNAL";
            unilateral: boolean;
            /**
             * @description What the user sets on the machine and keeps on the phone (seat, pad, grip; ADR-017). Labels:
             *     exerciseSetup.<field>.label.
             */
            setupFields: string[];
            /** @description Absent until the clips passed the filming checklist; the app then shows no demonstration. */
            clips?: components["schemas"]["ExerciseClips"];
        };
        /**
         * @description The two demonstration clips (ADR-017) — the first rep and the last rep near the target RIR. Paths in the app's
         *     assets (clips/<id>/first-rep.mp4, clips/<id>/last-rep.mp4).
         */
        ExerciseClips: {
            firstRep: string;
            lastRep: string;
        };
        /**
         * @description The program as it is this week: the deload ladder's calls in force today on the user's calendar (K-217) — a
         *     lighter week (`deload`, the sets of each exercise lowered), a week off (`restUntil`), the load held since a day
         *     (`loadHeldSince`: no load is added until the next rung).
         */
        Program: {
            deload?: components["schemas"]["DeloadWeek"];
            /**
             * Format: date
             * @description A week off in force; ends on its own after this day.
             */
            restUntil?: string;
            /** Format: date */
            loadHeldSince?: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            source: "GENERATED" | "OWN";
            days: components["schemas"]["ProgramDay"][];
        };
        /** @description A lighter week in force (K-217); ends on its own after `until`. */
        DeloadWeek: {
            setsFactor: number;
            /** Format: date */
            until: string;
        };
        /** @description A generated day names itself by nameKey (programDays.<day>.name, "Upper A"); a day of the user's own program by name. */
        ProgramDay: {
            /** Format: uuid */
            id: string;
            nameKey?: string;
            name?: string;
            weekday?: components["schemas"]["Weekday"];
            exercises: components["schemas"]["PlannedExercise"][];
        };
        PlannedExercise: {
            exerciseId: string;
            /** @description The program's sets. */
            baseSets: number;
            /** @description This week's sets (baseSets, or fewer in a deload). */
            sets: number;
            reps: components["schemas"]["RepRange"];
            targetRir: number;
            /** @description The load for the next session after progression and deload (K-217); absent until known. */
            nextLoadKg?: number;
            /** @description The reps to aim for next session (double progression, K-217); absent until known. */
            nextReps?: number;
        };
        /** @description min < max (a range to climb in, double progression); max at most 100. */
        RepRange: {
            min: number;
            max: number;
        };
        /**
         * @description The user's own program (K-211). Limits are keel.training's: a day's weekday is used once; exercises come from
         *     /v1/exercises; reps.max is above reps.min and at most 100.
         */
        OwnProgram: {
            days: {
                name: string;
                weekday?: components["schemas"]["Weekday"];
                exercises: {
                    exerciseId: string;
                    sets: number;
                    reps: components["schemas"]["RepRange"];
                }[];
            }[];
        };
        ProgramRequest: {
            /** @description 1 to 6 days; seven leave no rest day (G1 K-70). */
            trainingDays: components["schemas"]["Weekday"][];
        };
        NewWorkout: {
            clientId: components["schemas"]["ClientId"];
            /** Format: date-time */
            startedAt: string;
            /** Format: uuid */
            programDayId?: string;
        };
        /**
         * @description Finishing a workout of a program day sets each planned move's next load and reps (K-217, double progression).
         *     The moves whose form was not clean keep their load and reps (G6 K-31); each id once, from the catalog, else
         *     VALIDATION_FAILED.
         */
        WorkoutFinish: {
            /** Format: date-time */
            endedAt: string;
            uncleanExerciseIds?: string[];
        };
        Workout: {
            /** Format: uuid */
            id: string;
            clientId: components["schemas"]["ClientId"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string;
            /** Format: uuid */
            programDayId?: string;
            sets: components["schemas"]["LoggedSet"][];
        };
        /**
         * @description Only WORKING sets count toward effort and estimated 1RM (K-218). FAILURE is a set taken to failure: its rir is 0
         *     or absent.
         * @enum {string}
         */
        SetType: "WARM_UP" | "WORKING" | "DROP" | "FAILURE";
        /**
         * @description A unilateral exercise is logged per side (LEFT or RIGHT, required); any other exercise BOTH or absent.
         * @enum {string}
         */
        Side: "BOTH" | "LEFT" | "RIGHT";
        /**
         * @description One set. exerciseId may differ from the plan (a swap, e.g. pull-ups for lat pulldown). A
         *     BODYWEIGHT_PLUS_EXTERNAL exercise logs the added load in loadKg (0 without); a BODYWEIGHT exercise always 0. The
         *     engine adds the bodyweight. A set its exercise cannot have (see SetType, Side) is 400.
         */
        NewSet: {
            clientId: components["schemas"]["ClientId"];
            exerciseId: string;
            setType: components["schemas"]["SetType"];
            /** @description At most 2 decimals. */
            loadKg: number;
            reps: number;
            /** @description Reps left in the tank; absent when not given. */
            rir?: number;
            side?: components["schemas"]["Side"];
        };
        LoggedSet: components["schemas"]["NewSet"] & {
            /** Format: uuid */
            id: string;
        };
        /**
         * @description What the engine can be missing (its CheckIn) plus the scales the app asks with. Adherence is not asked: it is the
         *     week's consistency, counted from the logs (ADR-020 L-6).
         * @enum {string}
         */
        QuestionKind: "TRAINING" | "RECOVERY" | "SLEEP_QUALITY" | "ENERGY" | "LOOK" | "WAIST" | "APPETITE" | "CYCLE_STOPPED";
        Question: {
            kind: components["schemas"]["QuestionKind"];
            /** @enum {string} */
            format: "SCALE_1_10" | "CHOICE" | "CENTIMETRES";
            /** @description CHOICE only — the allowed answers. */
            choices?: string[];
            copyKey: string;
            /** @description Why this is asked, shown next to the question (U9). */
            reasonCopyKey: string;
        };
        CheckIn: {
            /**
             * Format: date
             * @description The check-in day of this week, in the user's time zone.
             */
            weekOf: string;
            questions: components["schemas"]["Question"][];
            answered: boolean;
        };
        /** @description One answer; exactly the field the question's format names is set. */
        Answer: {
            kind: components["schemas"]["QuestionKind"];
            scale?: number;
            choice?: string;
            cm?: number;
        };
        CheckInAnswers: {
            clientId: components["schemas"]["ClientId"];
            /**
             * Format: date
             * @description The check-in day these answers belong to (CheckIn.weekOf).
             */
            weekOf: string;
            answers: components["schemas"]["Answer"][];
        };
        Decision: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            madeOn: string;
            action: components["schemas"]["Action"];
            reasons: components["schemas"]["Reason"][];
            confidence: components["schemas"]["Confidence"];
            /** Format: date */
            nextReview: string;
            /** @description Where the words for this call live in en.json. */
            copyKey: string;
            application: components["schemas"]["Application"];
        };
        /**
         * @description Whether the call has changed the plan (K-216). A call that changes nothing is NOT_NEEDED; appliedAt once applied,
         *     undoneAt once undone.
         */
        Application: {
            /** @enum {string} */
            state: "NOT_NEEDED" | "PENDING" | "APPLIED" | "UNDONE";
            /** Format: date-time */
            appliedAt?: string;
            /** Format: date-time */
            undoneAt?: string;
        };
        DecisionPage: {
            items: components["schemas"]["Decision"][];
            /** @description The cursor for the next (older) page; absent on the last page. */
            next?: string;
        };
        Reason: {
            rule: string;
            source: components["schemas"]["Source"];
        };
        /** @description The rule's authority (U14): a research file and anchor, and what kind of source it is. */
        Source: {
            reference: string;
            tag: components["schemas"]["SourceTag"];
        };
        /** @enum {string} */
        SourceTag: "EXPERIENCE" | "LITERATURE" | "PRODUCT";
        /** @enum {string} */
        Confidence: "LOW" | "MEDIUM" | "HIGH";
        /** @enum {string} */
        Phase: "CUT" | "BULK";
        /** @description What the engine decided (the engine's sealed Action); `type` names the kind, the rest is its data. */
        Action: components["schemas"]["NoDecisionYet"] | components["schemas"]["Continue"] | components["schemas"]["AdjustCalories"] | components["schemas"]["IncreaseCalories"] | components["schemas"]["ChangeMovement"] | components["schemas"]["FixTraining"] | components["schemas"]["FixRecovery"] | components["schemas"]["FixAdherence"] | components["schemas"]["HardStop"] | components["schemas"]["StopLoadIncrease"] | components["schemas"]["Deload"] | components["schemas"]["FullRestWeek"] | components["schemas"]["MiniCut"] | components["schemas"]["ChangePhase"];
        /** @description Not enough data, or the window is not full — said, not guessed (U3). */
        NoDecisionYet: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "NO_DECISION_YET";
        };
        Continue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CONTINUE";
        };
        /** @description One calorie step on the daily target (K-107), e.g. -500 on a stalled cut, +250 on a stalled bulk. */
        AdjustCalories: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ADJUST_CALORIES";
            kcalPerDay: number;
        };
        /** @description The safety net narrowing a deficit (U13, K-104). */
        IncreaseCalories: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "INCREASE_CALORIES";
            kcalPerDay: number;
        };
        ChangeMovement: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CHANGE_MOVEMENT";
        };
        FixTraining: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "FIX_TRAINING";
        };
        FixRecovery: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "FIX_RECOVERY";
        };
        FixAdherence: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "FIX_ADHERENCE";
        };
        /** @description The one hard stop (U13): any deficit ends, maintenance at least, see a doctor. */
        HardStop: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "HARD_STOP";
        };
        StopLoadIncrease: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "STOP_LOAD_INCREASE";
        };
        /** @description A lighter week; weekly sets scale by setsFactor (K-110). */
        Deload: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "DELOAD";
            setsFactor: number;
        };
        FullRestWeek: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "FULL_REST_WEEK";
        };
        MiniCut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MINI_CUT";
            minWeeks: number;
            maxWeeks: number;
        };
        ChangePhase: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CHANGE_PHASE";
            to: components["schemas"]["Phase"];
        };
        /**
         * @description What the user follows today; each a plan number set by calls (ADR-020 L-13). Protein does not depend on calories
         *     and is always there; carbs and fat are absent when no split fits the target (the macro floors moved with a
         *     heavier trend or a birthday after the target was set). Before the first estimate there is no calorie target:
         *     GET /v1/targets is NOT_FOUND, and an apply or undo (a training call) answers with the steps and training days only.
         */
        Targets: {
            targetKcal?: number;
            proteinG?: number;
            carbsG?: number;
            fatG?: number;
            stepsPerDay: number;
            trainingSessionsPerWeek: number;
        };
        CoachQuestion: {
            text: string;
            /**
             * Format: uuid
             * @description The call the question is about, if any.
             */
            decisionId?: string;
        };
        CoachAnswer: {
            /** @description Words only; numbers in it come from the engine or the database (U1). */
            text: string;
        };
    };
    responses: {
        /** @description Any error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Stored (201), or already stored with this clientId (200) */
        WeighInCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["WeighIn"];
            };
        };
        /** @description Stored (201), or already stored with this clientId (200) */
        WaistMeasurementCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["WaistMeasurement"];
            };
        };
        /** @description Stored (201), or already stored with this clientId (200) */
        BodyLookCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BodyLook"];
            };
        };
        /** @description Stored (201), or already stored with this clientId (200) */
        PhotoCheckCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PhotoCheck"];
            };
        };
        /** @description Stored (201), or already stored with this clientId (200) */
        MealCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Meal"];
            };
        };
        /** @description Started (201), or already started with this clientId (200) */
        WorkoutCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Workout"];
            };
        };
        /** @description Stored (201), or already stored with this clientId (200) */
        SetCreated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LoggedSet"];
            };
        };
    };
    parameters: {
        Id: string;
        ConsentKind: components["schemas"]["ConsentKind"];
        /** @description First day, inclusive (local day). A range is at most 400 days. */
        From: string;
        /** @description Last day, inclusive */
        To: string;
        Day: string;
        Limit: number;
        /** @description The cursor of the last item already seen; omitted for the newest page */
        Before: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    signInWithApple: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppleSignIn"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description A new session; the old refresh token no longer works */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Deletion started; every module removes its own data (AccountDeletionRequested). The account is gone at once:
             *     from this answer on, its tokens get 401 — the phone signs out and drops its offline queue.
             */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    exportAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The export, one section per module */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountExport"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    putProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Profile"];
            };
        };
        responses: {
            /** @description The stored profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listConsents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per kind */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    grantConsent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["ConsentKind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentGrant"];
            };
        };
        responses: {
            /** @description Granted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    withdrawConsent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["ConsentKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Withdrawn */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listWeighIns: {
        parameters: {
            query: {
                /** @description First day, inclusive (local day). A range is at most 400 days. */
                from: components["parameters"]["From"];
                /** @description Last day, inclusive */
                to: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Weigh-ins in the range, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeighIn"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    recordWeighIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewWeighIn"];
            };
        };
        responses: {
            200: components["responses"]["WeighInCreated"];
            201: components["responses"]["WeighInCreated"];
            default: components["responses"]["Error"];
        };
    };
    deleteWeighIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getWeightTrend: {
        parameters: {
            query: {
                /** @description First day, inclusive (local day). A range is at most 400 days. */
                from: components["parameters"]["From"];
                /** @description Last day, inclusive */
                to: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One point per day that has a trend */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendPoint"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listWaistMeasurements: {
        parameters: {
            query: {
                /** @description First day, inclusive (local day). A range is at most 400 days. */
                from: components["parameters"]["From"];
                /** @description Last day, inclusive */
                to: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Waist measurements in the range, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaistMeasurement"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    recordWaistMeasurement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewWaistMeasurement"];
            };
        };
        responses: {
            200: components["responses"]["WaistMeasurementCreated"];
            201: components["responses"]["WaistMeasurementCreated"];
            default: components["responses"]["Error"];
        };
    };
    recordPhotoCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPhotoCheck"];
            };
        };
        responses: {
            200: components["responses"]["PhotoCheckCreated"];
            201: components["responses"]["PhotoCheckCreated"];
            default: components["responses"]["Error"];
        };
    };
    recordBodyLook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewBodyLook"];
            };
        };
        responses: {
            200: components["responses"]["BodyLookCreated"];
            201: components["responses"]["BodyLookCreated"];
            default: components["responses"]["Error"];
        };
    };
    putActivityDay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityDay"];
            };
        };
        responses: {
            /** @description Stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityDay"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    searchFoods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodSearch"];
            };
        };
        responses: {
            /** @description Best matches first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Food"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    lookUpBarcode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarcodeLookup"];
            };
        };
        responses: {
            /** @description The product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Food"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    estimateFood: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodEstimateRequest"];
            };
        };
        responses: {
            /** @description The estimate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodEstimate"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMeals: {
        parameters: {
            query: {
                day: components["parameters"]["Day"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The day's meals, in time order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    logMeal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewMeal"];
            };
        };
        responses: {
            200: components["responses"]["MealCreated"];
            201: components["responses"]["MealCreated"];
            default: components["responses"]["Error"];
        };
    };
    deleteMeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getDayBudget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The budget */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayBudget"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listExercises: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every exercise */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The program */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    putOwnProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnProgram"];
            };
        };
        responses: {
            /** @description The stored program */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    generateProgram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgramRequest"];
            };
        };
        responses: {
            /** @description The new program */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listWorkouts: {
        parameters: {
            query: {
                /** @description First day, inclusive (local day). A range is at most 400 days. */
                from: components["parameters"]["From"];
                /** @description Last day, inclusive */
                to: components["parameters"]["To"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workouts in the range, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workout"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewWorkout"];
            };
        };
        responses: {
            200: components["responses"]["WorkoutCreated"];
            201: components["responses"]["WorkoutCreated"];
            default: components["responses"]["Error"];
        };
    };
    getWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workout with its sets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workout"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    finishWorkout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutFinish"];
            };
        };
        responses: {
            /** @description The finished workout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workout"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    logSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSet"];
            };
        };
        responses: {
            200: components["responses"]["SetCreated"];
            201: components["responses"]["SetCreated"];
            default: components["responses"]["Error"];
        };
    };
    deleteSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                setId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getCurrentCheckIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The check-in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckIn"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    answerCheckIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInAnswers"];
            };
        };
        responses: {
            /** @description This week's call */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDecisions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description The cursor of the last item already seen; omitted for the newest page */
                before?: components["parameters"]["Before"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of calls */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCurrentDecision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current call */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The call */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    applyDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The targets after the call */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Targets"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    undoDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The targets after the undo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Targets"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTargets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The targets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Targets"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    askCoach: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachQuestion"];
            };
        };
        responses: {
            /** @description The answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachAnswer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
