package app.keel.engine;

import java.util.Locale;

/**
 * Every parameter the engine reads, with the file it lives in and the unit the code assumes. Values are never
 * here (K2): they come from data/parameters/*.yaml through {@link ParameterSet}. Loading fails if the files and
 * this list disagree (unknown key, missing key, other unit), so a renamed key or a kg→lb change cannot slip in.
 *
 * <p>quota.yaml is not listed: quotas are product limits for the coach, not engine rules (U14).
 */
public enum ParameterKey {
    WHTR_THRESHOLD(ParameterDomain.MEASUREMENT, Unit.RATIO),
    WAIST_CM_ELEVATED(ParameterDomain.MEASUREMENT, Unit.CM),
    WAIST_MEASUREMENT_ERROR_CM(ParameterDomain.MEASUREMENT, Unit.CM),
    WAIST_SIGNAL_MIN_SPAN_DAYS(ParameterDomain.MEASUREMENT, Unit.DAYS),
    RFM_INTERCEPT_PCT(ParameterDomain.MEASUREMENT, Unit.PERCENT_INTERNAL_ONLY),
    RFM_HEIGHT_TO_WAIST_PCT(ParameterDomain.MEASUREMENT, Unit.PERCENT_INTERNAL_ONLY),
    RFM_FEMALE_OFFSET_PCT(ParameterDomain.MEASUREMENT, Unit.PERCENT_INTERNAL_ONLY),
    RFM_PLAUSIBLE_MIN_PCT(ParameterDomain.MEASUREMENT, Unit.PERCENT_INTERNAL_ONLY),
    RFM_ENERGY_MARGIN_PCT(ParameterDomain.MEASUREMENT, Unit.PERCENT_INTERNAL_ONLY),
    LOOK_LEVEL_FIRST_PCT(ParameterDomain.MEASUREMENT, Unit.PERCENT_INTERNAL_ONLY),
    LOOK_LEVEL_STEP_PCT(ParameterDomain.MEASUREMENT, Unit.PERCENT_INTERNAL_ONLY),
    LOOK_LEVELS(ParameterDomain.MEASUREMENT, Unit.LEVELS),
    WEIGHT_DAILY_NOISE_SD_KG(ParameterDomain.MEASUREMENT, Unit.KG),
    PHOTO_MIN_DETECTABLE_FAT_MASS_KG(ParameterDomain.MEASUREMENT, Unit.KG),
    PHOTO_INTERVAL_WEEKS(ParameterDomain.MEASUREMENT, Unit.WEEKS),

    PROTEIN_G_PER_KG(ParameterDomain.NUTRITION, Unit.G_PER_KG_BODYWEIGHT),
    AMOUNT_ERROR_ESTIMATED_RATIO(ParameterDomain.NUTRITION, Unit.RATIO),
    AMOUNT_ERROR_MEASURED_RATIO(ParameterDomain.NUTRITION, Unit.RATIO),
    AMOUNT_ERROR_WEIGHED_RATIO(ParameterDomain.NUTRITION, Unit.RATIO),
    LABEL_VALUE_TOLERANCE_RATIO(ParameterDomain.NUTRITION, Unit.RATIO),
    ANALYSED_VALUE_ERROR_RATIO(ParameterDomain.NUTRITION, Unit.RATIO),
    PROTEIN_G_PER_KG_MAX(ParameterDomain.NUTRITION, Unit.G_PER_KG_BODYWEIGHT),
    PROTEIN_G_PER_KG_FEMALE_45_PLUS(ParameterDomain.NUTRITION, Unit.G_PER_KG_BODYWEIGHT),
    PROTEIN_FEMALE_HIGHER_FROM_AGE(ParameterDomain.NUTRITION, Unit.YEARS),
    FAT_G_PER_KG_MIN(ParameterDomain.NUTRITION, Unit.G_PER_KG_BODYWEIGHT),
    FAT_G_PER_KG_MAX(ParameterDomain.NUTRITION, Unit.G_PER_KG_BODYWEIGHT),
    CARBS_MIN_G_PER_DAY(ParameterDomain.NUTRITION, Unit.G_PER_DAY),
    FIBER_G_PER_DAY(ParameterDomain.NUTRITION, Unit.G_PER_DAY),
    CUT_STEP_MIN_KCAL(ParameterDomain.NUTRITION, Unit.KCAL_PER_DAY),
    BULK_STEP_KCAL(ParameterDomain.NUTRITION, Unit.KCAL_PER_DAY),
    DEFICIT_STOP_FAT_PROXY_PCT(ParameterDomain.SAFETY, Unit.PERCENT_INTERNAL_ONLY),
    STEPS_TARGET_START(ParameterDomain.NUTRITION, Unit.STEPS_PER_DAY),
    STEPS_TARGET_RAISED(ParameterDomain.NUTRITION, Unit.STEPS_PER_DAY),
    CALORIE_CHANGE_MIN_WAIT_WEEKS(ParameterDomain.NUTRITION, Unit.WEEKS),
    GAIN_RATE_IDEAL_KG_PER_MONTH(ParameterDomain.NUTRITION, Unit.KG_PER_MONTH),
    GAIN_RATE_MAX_KG_PER_MONTH(ParameterDomain.NUTRITION, Unit.KG_PER_MONTH),
    MAINTENANCE_OBSERVATION_DAYS(ParameterDomain.NUTRITION, Unit.DAYS),
    RESTING_KCAL_PER_KG(ParameterDomain.NUTRITION, Unit.KCAL_PER_KG_PER_DAY),
    RESTING_KCAL_PER_CM(ParameterDomain.NUTRITION, Unit.KCAL_PER_CM_PER_DAY),
    RESTING_KCAL_PER_YEAR(ParameterDomain.NUTRITION, Unit.KCAL_PER_YEAR_PER_DAY),
    RESTING_KCAL_OFFSET(ParameterDomain.NUTRITION, Unit.KCAL_OFFSET_PER_DAY),
    ACTIVITY_FACTOR_INACTIVE(ParameterDomain.NUTRITION, Unit.ACTIVITY_FACTOR),
    ACTIVITY_FACTOR_LOW_ACTIVE(ParameterDomain.NUTRITION, Unit.ACTIVITY_FACTOR),
    ACTIVITY_FACTOR_ACTIVE(ParameterDomain.NUTRITION, Unit.ACTIVITY_FACTOR),
    ACTIVITY_FACTOR_VERY_ACTIVE(ParameterDomain.NUTRITION, Unit.ACTIVITY_FACTOR),
    ACTIVITY_FACTOR_UNKNOWN(ParameterDomain.NUTRITION, Unit.ACTIVITY_FACTOR),
    MAINTENANCE_ESTIMATE_ERROR(ParameterDomain.NUTRITION, Unit.RATIO),
    ENERGY_PER_KG_WEIGHT_CHANGE(ParameterDomain.NUTRITION, Unit.KCAL_PER_KG_WEIGHT_CHANGE),
    LOGGING_BIAS_DAILY_SMOOTHING(ParameterDomain.NUTRITION, Unit.RATIO),
    LOGGING_BIAS_MIN_WINDOWS(ParameterDomain.NUTRITION, Unit.WINDOWS),
    MIN_LOGGED_DAYS_PER_WEEK(ParameterDomain.NUTRITION, Unit.DAYS_PER_WEEK),
    BULK_STALL_WEEKS(ParameterDomain.NUTRITION, Unit.WEEKS),
    MINI_CUT_AFTER_BULK_MONTHS(ParameterDomain.NUTRITION, Unit.MONTHS),
    MINI_CUT_WEEKS_MIN(ParameterDomain.NUTRITION, Unit.WEEKS),
    MINI_CUT_WEEKS_MAX(ParameterDomain.NUTRITION, Unit.WEEKS),

    WEEKLY_LOSS_CAP_KG(ParameterDomain.SAFETY, Unit.KG_PER_WEEK),
    WEEKLY_LOSS_CAP_PCT_BODYWEIGHT(ParameterDomain.SAFETY, Unit.RATIO),
    BMR_FLOOR_ENABLED(ParameterDomain.SAFETY, Unit.BOOLEAN),
    RAPID_LOSS_NARROW_PCT(ParameterDomain.SAFETY, Unit.RATIO),
    RAPID_LOSS_WINDOW_WEEKS(ParameterDomain.SAFETY, Unit.WEEKS),
    LEA_THRESHOLD_KCAL_PER_KG_FFM(ParameterDomain.SAFETY, Unit.KCAL_PER_KG_FFM_PER_DAY),
    EA_WARNING_KCAL_PER_KG_FFM(ParameterDomain.SAFETY, Unit.KCAL_PER_KG_FFM_PER_DAY),
    EA_ADEQUATE_KCAL_PER_KG_FFM(ParameterDomain.SAFETY, Unit.KCAL_PER_KG_FFM_PER_DAY),
    BULK_CEILING_FAT_PROXY_PCT(ParameterDomain.SAFETY, Unit.PERCENT_INTERNAL_ONLY),
    FAT_FIRST_FAT_PROXY_PCT(ParameterDomain.SAFETY, Unit.PERCENT_INTERNAL_ONLY),
    SURPLUS_BELOW_FAT_PROXY_PCT(ParameterDomain.SAFETY, Unit.PERCENT_INTERNAL_ONLY),

    TARGET_RIR_MAX(ParameterDomain.TRAINING, Unit.REPS_IN_RESERVE),
    CALIBRATION_RIR_MIN(ParameterDomain.TRAINING, Unit.REPS_IN_RESERVE),
    E1RM_EPLEY_DIVISOR(ParameterDomain.TRAINING, Unit.REPS),
    ARM_WEEKLY_SETS_MIN(ParameterDomain.TRAINING, Unit.SETS_PER_WEEK),
    REP_RANGE_COMPOUND_MIN(ParameterDomain.TRAINING, Unit.REPS),
    REP_RANGE_COMPOUND_MAX(ParameterDomain.TRAINING, Unit.REPS),
    REP_RANGE_ISOLATION_MIN(ParameterDomain.TRAINING, Unit.REPS),
    REP_RANGE_ISOLATION_MAX(ParameterDomain.TRAINING, Unit.REPS),
    E1RM_MAX_REPS_TO_FAILURE(ParameterDomain.TRAINING, Unit.REPS),
    WEEKLY_SETS_PER_MUSCLE(ParameterDomain.TRAINING, Unit.SETS_PER_WEEK),
    SETS_PER_SESSION_PER_MUSCLE_MIN(ParameterDomain.TRAINING, Unit.SETS),
    SETS_PER_SESSION_PER_MUSCLE_MAX(ParameterDomain.TRAINING, Unit.SETS),
    FREQUENCY_PER_MUSCLE_PER_WEEK(ParameterDomain.TRAINING, Unit.SESSIONS_PER_WEEK),
    DEFAULT_TRAINING_DAYS_PER_WEEK(ParameterDomain.TRAINING, Unit.DAYS_PER_WEEK),
    LOAD_INCREMENT_UPPER_KG(ParameterDomain.TRAINING, Unit.KG),
    LOAD_INCREMENT_LOWER_KG(ParameterDomain.TRAINING, Unit.KG),
    LOAD_JUMP_MAX_STEPS(ParameterDomain.TRAINING, Unit.LOAD_STEPS),
    REP_CEILING_ABOVE_RANGE(ParameterDomain.TRAINING, Unit.REPS),
    RETURN_STEP_BACK_AFTER_WEEKS(ParameterDomain.TRAINING, Unit.WEEKS),
    BUSY_MIN_SESSIONS_PER_WEEK(ParameterDomain.TRAINING, Unit.SESSIONS_PER_WEEK),
    BUSY_MIN_SETS_PER_EXERCISE(ParameterDomain.TRAINING, Unit.SETS),
    BUSY_MIN_KEEP_LOAD(ParameterDomain.TRAINING, Unit.BOOLEAN),
    BUSY_MIN_OLDER_AGE(ParameterDomain.TRAINING, Unit.YEARS),
    BUSY_MIN_SESSIONS_PER_WEEK_OLDER(ParameterDomain.TRAINING, Unit.SESSIONS_PER_WEEK),
    BUSY_MIN_SETS_PER_EXERCISE_OLDER(ParameterDomain.TRAINING, Unit.SETS),
    LOAD_PROGRESSION_COMPOUND_ONLY(ParameterDomain.TRAINING, Unit.BOOLEAN),
    TECHNIQUE_GATE_REQUIRED(ParameterDomain.TRAINING, Unit.BOOLEAN),
    STAGNATION_DELOAD_MONTHS(ParameterDomain.TRAINING, Unit.MONTHS),
    PLATEAU_SESSIONS(ParameterDomain.TRAINING, Unit.SESSIONS),
    OVERTRAINING_MISSED_PLAN_WEEKS(ParameterDomain.TRAINING, Unit.WEEKS),
    MISSED_SESSIONS_IN_A_ROW(ParameterDomain.WINDOWS, Unit.SESSIONS),
    HUNGER_QUESTION_DAYS(ParameterDomain.WINDOWS, Unit.DAYS),
    FIRST_WEEKS(ParameterDomain.WINDOWS, Unit.WEEKS),
    FIRST_WEEKS_RISK_FROM(ParameterDomain.WINDOWS, Unit.WEEKS),
    DELOAD_VOLUME_FACTOR(ParameterDomain.TRAINING, Unit.RATIO),
    DELOAD_LOAD_REDUCTION_MIN(ParameterDomain.TRAINING, Unit.RATIO),
    DELOAD_LOAD_REDUCTION_MAX(ParameterDomain.TRAINING, Unit.RATIO),

    TREND_DISPLAY_DAYS(ParameterDomain.WINDOWS, Unit.DAYS),
    DECISION_WINDOW_DAYS(ParameterDomain.WINDOWS, Unit.DAYS),
    NO_INTERPRETATION_DAYS(ParameterDomain.WINDOWS, Unit.DAYS),
    EVALUATION_WINDOW_DAYS(ParameterDomain.WINDOWS, Unit.DAYS),
    MIN_WEIGHINS_PER_WEEK(ParameterDomain.WINDOWS, Unit.WEIGHINS_PER_WEEK),
    ON_TRACK_MIN_RATIO(ParameterDomain.WINDOWS, Unit.RATIO),
    ADHERENCE_FIX_BELOW(ParameterDomain.WINDOWS, Unit.RATIO),
    WHAT_IF_TREND_STEP_MARGINS(ParameterDomain.WINDOWS, Unit.MARGINS),
    WHAT_IF_CUT_STEP_OF_LOSS_CAP(ParameterDomain.WINDOWS, Unit.RATIO),
    FLAT_MARGIN_KG(ParameterDomain.WINDOWS, Unit.KG),
    FLAT_WAIT_WEEKS(ParameterDomain.WINDOWS, Unit.WEEKS),
    DENSE_WEIGHINS_PER_WEEK(ParameterDomain.WINDOWS, Unit.WEIGHINS_PER_WEEK),

    ENERGY_MODEL_GLYCOGEN_MJ_PER_KG(ParameterDomain.PROJECTION, Unit.MJ_PER_KG),
    ENERGY_MODEL_GLYCOGEN_START_KG(ParameterDomain.PROJECTION, Unit.KG),
    ENERGY_MODEL_GLYCOGEN_WATER_G_PER_G(ParameterDomain.PROJECTION, Unit.G_PER_G),
    ENERGY_MODEL_CARB_ENERGY_SHARE(ParameterDomain.PROJECTION, Unit.RATIO),
    ENERGY_MODEL_SODIUM_MG_PER_ML(ParameterDomain.PROJECTION, Unit.MG_PER_ML),
    ENERGY_MODEL_SODIUM_CLEARANCE_MG_PER_L_PER_DAY(ParameterDomain.PROJECTION, Unit.MG_PER_L_PER_DAY),
    ENERGY_MODEL_CARB_SODIUM_MG_PER_DAY(ParameterDomain.PROJECTION, Unit.MG_PER_DAY),
    ENERGY_MODEL_FAT_MJ_PER_KG(ParameterDomain.PROJECTION, Unit.MJ_PER_KG),
    ENERGY_MODEL_LEAN_MJ_PER_KG(ParameterDomain.PROJECTION, Unit.MJ_PER_KG),
    ENERGY_MODEL_FORBES_KG(ParameterDomain.PROJECTION, Unit.KG),
    ENERGY_MODEL_START_FAT_PCT_PER_YEAR(ParameterDomain.PROJECTION, Unit.PERCENT_PER_YEAR_INTERNAL_ONLY),
    ENERGY_MODEL_START_FAT_PCT_PER_LN_BMI(ParameterDomain.PROJECTION, Unit.PERCENT_PER_LN_BMI_INTERNAL_ONLY),
    ENERGY_MODEL_START_FAT_PCT_OFFSET(ParameterDomain.PROJECTION, Unit.PERCENT_OFFSET_INTERNAL_ONLY),
    ENERGY_MODEL_FAT_RESTING_KJ_PER_KG_PER_DAY(ParameterDomain.PROJECTION, Unit.KJ_PER_KG_PER_DAY),
    ENERGY_MODEL_LEAN_RESTING_KJ_PER_KG_PER_DAY(ParameterDomain.PROJECTION, Unit.KJ_PER_KG_PER_DAY),
    ENERGY_MODEL_FAT_SYNTHESIS_KJ_PER_KG(ParameterDomain.PROJECTION, Unit.KJ_PER_KG),
    ENERGY_MODEL_LEAN_SYNTHESIS_KJ_PER_KG(ParameterDomain.PROJECTION, Unit.KJ_PER_KG),
    ENERGY_MODEL_THERMIC_EFFECT_RATIO(ParameterDomain.PROJECTION, Unit.RATIO),
    ENERGY_MODEL_ADAPTIVE_RATIO(ParameterDomain.PROJECTION, Unit.RATIO),
    ENERGY_MODEL_ADAPTIVE_DAYS(ParameterDomain.PROJECTION, Unit.DAYS),
    PROJECTION_MIN_AGE(ParameterDomain.PROJECTION, Unit.YEARS),
    PROJECTION_LOSS_MIN_BMI(ParameterDomain.PROJECTION, Unit.KG_PER_M2),
    PROJECTION_MIN_BMI(ParameterDomain.PROJECTION, Unit.KG_PER_M2),
    PROJECTION_MIN_SPAN_DAYS(ParameterDomain.PROJECTION, Unit.DAYS),
    PROJECTION_HORIZON_WEEKS(ParameterDomain.PROJECTION, Unit.WEEKS),
    PROJECTION_ADHERENCE_LOW(ParameterDomain.PROJECTION, Unit.RATIO),
    PROJECTION_ADHERENCE_MID(ParameterDomain.PROJECTION, Unit.RATIO),
    PROJECTION_ADHERENCE_HIGH(ParameterDomain.PROJECTION, Unit.RATIO),
    PROJECTION_MAINTENANCE_UNCERTAINTY_KJ_PER_DAY(ParameterDomain.PROJECTION, Unit.KJ_PER_DAY),
    PROJECTION_ERROR_FLOOR_KG(ParameterDomain.PROJECTION, Unit.KG),
    PROJECTION_MIN_GAP_KCAL(ParameterDomain.PROJECTION, Unit.KCAL_PER_DAY);

    private final ParameterDomain domain;
    private final Unit unit;

    ParameterKey(ParameterDomain domain, Unit unit) {
        this.domain = domain;
        this.unit = unit;
    }

    /** The key as written in the YAML files, e.g. {@code decision_window_days}. */
    public String yamlKey() {
        return name().toLowerCase(Locale.ROOT);
    }

    public ParameterDomain domain() {
        return domain;
    }

    public Unit unit() {
        return unit;
    }
}
